# Server configuration
server.port=8081

# Application name
spring.application.name=redis-starter

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.example.gemfirestarter=DEBUG
logging.level.org.springframework.data.redis=INFO

# Redis configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=
spring.redis.timeout=60000

# Redis cache TTL (Time-To-Live) settings
spring.cache.redis.time-to-live=3600000

# Redis connection pool settings
spring.redis.jedis.pool.max-active=8
spring.redis.jedis.pool.max-idle=8
spring.redis.jedis.pool.min-idle=0