# Server configuration 
server.port=8081

# Application name
spring.application.name=redis-starter

# Redis configuration  
spring.redis.host=localhost
spring.redis.port=6379

# serializer
spring.redis.serializer.value=json

# logging
logging.level.org.springframework.data.redis.core=debug